language: bash

services:
  - docker

before_script:
  - docker build . --tag=component-generator

after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
