sudo: required
language: bash
services:
  - docker

before_script:
  - docker build . --tag=my-component
  - docker run -e KBC_DATADIR=/code/tests/data/ my-component /code/tests/tests.sh
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
